#if PI_TENSORLIB_ENABLE_HIP && !PI_TENSORLIB_ENABLE_CUDA
#include <kernels_amd.h>

#if AMD_KERNEL_ARCH == 942
DECLARE_ALL_KERNELS(gfx942);
DECLARE_KERNEL_ALIASES(gfx942);
DECLARE_EXTRA_KERNELS(gfx942);
DECLARE_EXTRA_KERNEL_ALIASES(gfx942);
#elif AMD_KERNEL_ARCH == 1101
DECLARE_ALL_KERNELS(gfx1101);
DECLARE_KERNEL_ALIASES(gfx1101);
DECLARE_EXTRA_KERNELS(gfx1101);
DECLARE_EXTRA_KERNEL_ALIASES(gfx1101);
#endif
#else
#include <kernels_nv.h>

#if NV_KERNEL_ARCH == 80
DECLARE_ALL_KERNELS(sm80);
DECLARE_KERNEL_ALIASES(sm80);
#elif NV_KERNEL_ARCH == 89
DECLARE_ALL_KERNELS(sm89);
DECLARE_KERNEL_ALIASES(sm89);
#elif NV_KERNEL_ARCH == 90
DECLARE_ALL_KERNELS(sm90);
DECLARE_KERNEL_ALIASES(sm90);
#elif NV_KERNEL_ARCH == 100
DECLARE_ALL_KERNELS(sm100);
DECLARE_KERNEL_ALIASES(sm100);
#endif
#endif
