#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PYTHON_BIN=${PYTHON_BIN:-"${SCRIPT_DIR}/.venv/bin/python"}

(cd "test_act" && "$PYTHON_BIN" reference_impl.py)
(cd "test_action_model_streaming_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_action_model_streaming_bwd_supplier" && "$PYTHON_BIN" reference_impl.py)
(cd "test_addmm_gelu_mlp" && "$PYTHON_BIN" reference_impl.py)
(cd "test_attention_block" && "$PYTHON_BIN" reference_impl.py)
(cd "test_attention_block" && FBAMTRAIN_REF_DTYPE=fp16 "$PYTHON_BIN" reference_impl.py)
(cd "test_avg_pool1d" && "$PYTHON_BIN" reference_impl.py)
(cd "test_avg_pool2d" && "$PYTHON_BIN" reference_impl.py)
(cd "test_build_cell_embed" && "$PYTHON_BIN" reference_impl.py)
(cd "test_conv2d" && "$PYTHON_BIN" reference_impl.py)
(cd "test_conv2d_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_conv2d_fp16acc" && "$PYTHON_BIN" reference_impl.py)
(cd "test_cross_entropy" && "$PYTHON_BIN" reference_impl.py)
(cd "test_cross_entropy_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_cross_entropy_lm_head_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_div" && "$PYTHON_BIN" reference_impl.py)
(cd "test_div_add" && "$PYTHON_BIN" reference_impl.py)
(cd "test_embedding" && "$PYTHON_BIN" reference_impl.py)
(cd "test_frame_head" && "$PYTHON_BIN" reference_impl.py)
(cd "test_frame_head_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_layer_norm" && "$PYTHON_BIN" reference_impl.py)
(cd "test_linear_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_cell_fwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_fwd_simple" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_fwd_streaming_large" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_streaming_ce" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_streaming_torch" && "$PYTHON_BIN" reference_impl.py)
(cd "test_lstm_streaming_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_matmul_fp32_out" && "$PYTHON_BIN" reference_impl.py)
(cd "test_matmul_large_shape" && "$PYTHON_BIN" reference_impl.py)
(cd "test_matmul_transpose" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mean" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mean_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_and_reshape_fwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_bwd" && MHA_TEST_HEADS_LIST=4 "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_bwd" && MHA_TEST_HEADS_LIST=8 MHA_TEST_SEQLEN_LIST=480 "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_bwd_core" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_fwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mha_attn_fwd" && MHA_TEST_BATCH=2 MHA_TEST_SEQLEN=480 "$PYTHON_BIN" reference_impl.py)
(cd "test_mlp_block" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mlp_block_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mm_gelu_mlp" && "$PYTHON_BIN" reference_impl.py)
(cd "test_mul" && "$PYTHON_BIN" reference_impl.py)
(cd "test_optimizer_adamw" && "$PYTHON_BIN" reference_impl.py)
(cd "test_optimizer_muon" && "$PYTHON_BIN" reference_impl.py)
(cd "test_rms_norm" && "$PYTHON_BIN" reference_impl.py)
(cd "test_rms_norm_bwd" && "$PYTHON_BIN" reference_impl.py)
(cd "test_trailing_broadcast_add" && "$PYTHON_BIN" reference_impl.py)
