// Auto-generated by generate_conv2d_bins.py. Do not edit.

#pragma once

#include <array>
#include <cstdint>

#include <kernels/kernel_binaries.h>

struct Conv2dBinKey
{
    uint32_t batch;
    uint32_t height;
    uint32_t width;
};

struct Conv2dBinKernelKey
{
    uint32_t in_channels;
    uint32_t out_channels;
    uint32_t kernel_h;
    uint32_t kernel_w;
    uint32_t stride_h;
    uint32_t stride_w;
    uint32_t dilation_h;
    uint32_t dilation_w;
};

enum class CutlassConv2dBinImplementation : uint8_t
{
    Cutlass2,
    Cutlass3,
};

struct CutlassConv2dBinKernelEntry
{
    Conv2dBinKernelKey key;
    std::array<uint32_t, 2> padding;
    Conv2dBinKey bin;
    CutlassConv2dBinImplementation implementation;
    const kernel_bin_t<kernel_meta_conv2d_cutlass_t> *bf16_kernel;
    const kernel_bin_t<kernel_meta_conv2d_cutlass_t> *fp16_kernel;
    const kernel_bin_t<kernel_meta_conv2d_cutlass_t> *fp16_acc_fp16_kernel;
};

struct CutlassConv2dBwdBinKernelEntry
{
    Conv2dBinKernelKey key;
    std::array<uint32_t, 2> padding;
    Conv2dBinKey bin;
    CutlassConv2dBinImplementation implementation;
    const kernel_bin_t<kernel_meta_conv2d_cutlass_t> *bf16_kernel;
    const kernel_bin_t<kernel_meta_conv2d_cutlass_t> *fp16_kernel;
};

#if PI_TENSORLIB_ENABLE_CUDA
inline constexpr std::array<uint32_t, 1> kCutlassConv2dCutlass3Architectures{{90}};
constexpr bool IsCutlassConv2dCutlass3Architecture(const uint32_t architecture)
{
    for (const uint32_t supported : kCutlassConv2dCutlass3Architectures)
    {
        if (supported == architecture)
        {
            return true;
        }
    }
    return false;
}

inline constexpr std::array<CutlassConv2dBinKernelEntry, 2> kCutlassConv2dBinKernels{{
    CutlassConv2dBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 24, 80}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80, &kconv2d_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80, &kconv2d_cutlass_fp16_acc_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80},
    CutlassConv2dBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 48, 160}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160, &kconv2d_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160, &kconv2d_cutlass_fp16_acc_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160},
}};

inline constexpr std::array<CutlassConv2dBwdBinKernelEntry, 2> kCutlassConv2dDgradBinKernels{{
    CutlassConv2dBwdBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 24, 80}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_dgrad_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80, &kconv2d_dgrad_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80},
    CutlassConv2dBwdBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 48, 160}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_dgrad_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160, &kconv2d_dgrad_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160},
}};

inline constexpr std::array<CutlassConv2dBwdBinKernelEntry, 2> kCutlassConv2dWgradBinKernels{{
    CutlassConv2dBwdBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 24, 80}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_wgrad_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80, &kconv2d_wgrad_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h24_w80},
    CutlassConv2dBwdBinKernelEntry{{1024, 1024, 3, 3, 1, 1, 2, 2}, {2, 2}, {32, 48, 160}, (IsCutlassConv2dCutlass3Architecture(NV_KERNEL_ARCH) ? CutlassConv2dBinImplementation::Cutlass3 : CutlassConv2dBinImplementation::Cutlass2), &kconv2d_wgrad_cutlass_bf16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160, &kconv2d_wgrad_cutlass_fp16_stride1_pad2_dil2_ic1024_oc1024_b32_h48_w160},
}};
#else
inline constexpr std::array<CutlassConv2dBinKernelEntry, 0> kCutlassConv2dBinKernels{};
inline constexpr std::array<CutlassConv2dBwdBinKernelEntry, 0> kCutlassConv2dDgradBinKernels{};
inline constexpr std::array<CutlassConv2dBwdBinKernelEntry, 0> kCutlassConv2dWgradBinKernels{};
#endif
